import { CopyLinkButton } from '@/components/events/CopyLinkButton'
import { Card, CardContent, CardHeader } from '@/components/ui/Card'
import { requirePhotographer } from '@/lib/account/photographers'
import { formatEventDate } from '@/lib/events/format'
import { getOrCreateEventQrCode, getOwnedEventOrNotFound } from '@/lib/events/service'
import { eventUploadUrl } from '@/lib/events/url'
import { EVENT_TYPE_LABELS } from '@/lib/validation/events'
import { qrSvg } from '@/lib/qr'
import { cn } from '@/lib/utils'

interface Props {
  params: Promise<{ id: string }>
}

const downloadBtnClasses =
  'inline-flex h-8 items-center justify-center rounded-md bg-zinc-100 px-3 text-sm font-medium text-zinc-900 transition-colors hover:bg-zinc-200'

export default async function EventOverviewPage({ params }: Props) {
  const { id } = await params
  const { user } = await requirePhotographer()
  const event = await getOwnedEventOrNotFound(id, user.id)

  const qr = await getOrCreateEventQrCode(event)
  const uploadUrl = eventUploadUrl(event.slug)
  const qrMarkup = await qrSvg(uploadUrl, 220)

  return (
    <div className="grid gap-6 md:grid-cols-3">
      <Card className="md:col-span-2">
        <CardHeader>
          <h2 className="font-semibold">Event details</h2>
        </CardHeader>
        <CardContent>
          <dl className="grid grid-cols-1 gap-4 text-sm sm:grid-cols-2">
            <Detail label="Title" value={event.name} />
            <Detail label="Type" value={EVENT_TYPE_LABELS[event.eventType]} />
            <Detail label="Date" value={formatEventDate(event.eventDate)} />
            <Detail label="Venue" value={event.venue ?? '—'} />
            <Detail label="Status" value={event.status} className="capitalize" />
          </dl>
          {event.description && <p className="mt-6 text-sm text-zinc-600">{event.description}</p>}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <h2 className="font-semibold">Guest upload QR</h2>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          <div
            className="mx-auto h-[220px] w-[220px] rounded border border-zinc-200 bg-white p-2 [&>svg]:h-full [&>svg]:w-full"
            // Trusted, deterministic markup generated by `qrcode` from a URL we control.
            dangerouslySetInnerHTML={{ __html: qrMarkup }}
          />
          <p className="text-zinc-500">Print or share this code — guests scan it to upload.</p>
          <code className="block rounded bg-zinc-100 px-2 py-1 text-xs break-all">{uploadUrl}</code>
          <div className="flex flex-wrap gap-2">
            <CopyLinkButton url={uploadUrl} />
            <a
              href={`/api/events/${event.id}/qr`}
              download={`${event.slug}-qr.png`}
              className={downloadBtnClasses}
            >
              Download PNG
            </a>
          </div>
          {!qr.isActive && (
            <p className="text-xs text-amber-600">This QR link is currently deactivated.</p>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function Detail({ label, value, className }: { label: string; value: string; className?: string }) {
  return (
    <div>
      <dt className="text-zinc-400">{label}</dt>
      <dd className={cn('mt-0.5 text-zinc-900', className)}>{value}</dd>
    </div>
  )
}
