import { CopyLinkButton } from '@/components/events/CopyLinkButton'
import { Card, CardContent, CardHeader } from '@/components/ui/Card'
import { DownloadIcon } from '@/components/ui/icons'
import { requirePhotographer } from '@/lib/account/photographers'
import { formatEventDate } from '@/lib/events/format'
import { getOrCreateEventQrCode, getOwnedEventOrNotFound } from '@/lib/events/service'
import { eventUploadUrl } from '@/lib/events/url'
import { EVENT_TYPE_LABELS } from '@/lib/validation/events'
import { qrSvg } from '@/lib/qr'
import { cn } from '@/lib/utils'

interface Props {
  params: Promise<{ id: string }>
}

const downloadBtnClasses =
  'inline-flex h-9 items-center justify-center gap-1.5 rounded-md bg-secondary px-3 text-body-sm font-medium text-secondary-foreground transition hover:bg-sand-200 dark:hover:brightness-125 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background'

export default async function EventOverviewPage({ params }: Props) {
  const { id } = await params
  const { user } = await requirePhotographer()
  const event = await getOwnedEventOrNotFound(id, user.id)

  const qr = await getOrCreateEventQrCode(event)
  const uploadUrl = eventUploadUrl(event.slug)
  const qrMarkup = await qrSvg(uploadUrl, 220)

  return (
    <div className="grid gap-6 md:grid-cols-3">
      <Card className="md:col-span-2">
        <CardHeader>
          <h2 className="font-display text-h3 text-foreground">Event details</h2>
        </CardHeader>
        <CardContent>
          <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <Detail label="Title" value={event.name} />
            <Detail label="Type" value={EVENT_TYPE_LABELS[event.eventType]} />
            <Detail label="Date" value={formatEventDate(event.eventDate)} />
            <Detail label="Venue" value={event.venue ?? '—'} />
            <Detail label="Status" value={event.status} className="capitalize" />
          </dl>
          {event.description && (
            <p className="mt-6 text-body-sm text-muted-foreground">{event.description}</p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <h2 className="font-display text-h3 text-foreground">Guest upload QR</h2>
        </CardHeader>
        <CardContent className="space-y-4">
          <div
            className="mx-auto h-[220px] w-[220px] rounded-xl border border-border bg-white p-3 [&>svg]:h-full [&>svg]:w-full"
            // Trusted, deterministic markup generated by `qrcode` from a URL we control.
            dangerouslySetInnerHTML={{ __html: qrMarkup }}
          />
          <p className="text-body-sm text-muted-foreground">
            Print it or show it on a screen — guests scan to upload.
          </p>
          <code className="block truncate rounded-md bg-muted px-3 py-2 text-caption text-muted-foreground">
            {uploadUrl}
          </code>
          <div className="flex flex-wrap gap-2">
            <CopyLinkButton url={uploadUrl} />
            <a
              href={`/api/events/${event.id}/qr`}
              download={`${event.slug}-qr.png`}
              className={downloadBtnClasses}
            >
              <DownloadIcon className="size-4" /> Download PNG
            </a>
          </div>
          {!qr.isActive && (
            <p className="text-caption text-warning-subtle-foreground">
              This QR link is currently deactivated.
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function Detail({ label, value, className }: { label: string; value: string; className?: string }) {
  return (
    <div>
      <dt className="text-overline uppercase text-muted-foreground">{label}</dt>
      <dd className={cn('mt-1 text-body-sm text-foreground', className)}>{value}</dd>
    </div>
  )
}
